### ISSUE TITLE
找不到育碧的安装路径

### ISSUE THREAD

**Issue by steadyoak** [dyang886/Game-Save-Manager#2]
然后弹出了错误
Traceback (most recent call last):
  File "gamesave.py", line 1906, in <module>
  File "gamesave.py", line 390, in __init__
  File "gamesave.py", line 787, in vampire_survivors
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:/Users/xxxx/AppData/Roaming'

然后退出了

**Comment by dyang886** [comment]
找不到指定路径问题已解决，下个版本更新，在这之前可手动创建路径 C:/Users/xxxx/AppData/Roaming

关于找不到育碧安装路径，请提供注册表截图以便找出问题：
1. Win+R 输入 regedit
2. 在上方路径复制粘贴 Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ubisoft\Launcher
3. 截图当前整个注册表界面
